version: 2.1

commands:
  install_build_tools:
    steps:
      - run:
          name: Install conan and build tools
          command: |
            brew install conan cmake

  build_recipe:
    steps:
      - run:
          name: Build conan recipe
          command: |
            conan create . proofofwork/stable

  upload_conan_package:
    steps:
      - run:
          name: Upload conan package
          command: |
            conan remote add proofofwork https://pow.jfrog.io/artifactory/api/conan/proofofwork
            conan user -p $CONAN_PASSWORD -r proofofwork $CONAN_USERNAME
            conan upload SECP256K1/0.1@proofofwork/stable --all -r proofofwork --confirm

jobs:

  build: 
    macos:
      xcode: 11.3.0
    steps:
      - install_build_tools
      - checkout
      - build_recipe
      - upload_conan_package
          
workflows:
  test_build:
    jobs:
      - build